[workspace]
members = [
    "cortex-m4-binary",
    "esp32-binary",
    "web-server",
]
resolver = "2"

[workspace.package]
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
overflow-checks = true
